version: 2.1
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      product: Risky Repo
      subProduct: Risky subpro
      environment: Staging
      token: $AMC_TOKEN
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
    steps:
      - run:
          name: "Armorcode Validate"
          command: |
              wget https://dev.armorcode.ai/static/scripts/slastatus.sh
              sh slastatus.sh
workflows:
  armorcode-validation-workflow:
    jobs:
      - armorcode-validate
