version: 2.1
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      product: AMCT QA R-77
      subProduct: Github 101
      environment: Staging
      token: $ARMORCODE_SLA_TOKEN
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
    steps:
      - run:
          name: "Armorcode Validate"
          echo: $ARMORCODE_SLA_TOKEN
          command: |
              wget https://qa.armorcode.ai/static/scripts/slastatus.sh
              sh slastatus.sh
workflows:    
  armorcode-validation-workflow:
    jobs:
      - build:
         context:
           - my-context
      - armorcode-validate
