--- 
jobs: 
  armorcode-validate: 
    docker: 
      - 
        image: byrnedo/alpine-curl
    environment: 
      buildNumber: "<< pipeline.number >>"
      buildTool: CIRCLE_CI
      environment: Staging
      product: "Risky Repo"
      subProduct: "Risky subpro"
      token: "${ARMORCODE_SLA_TOKEN1}"
    steps: 
      - 
        run: 
          command: |
              wget https://1169-44-239-74-14.ngrok.io/static/scripts/slastatus.sh
              sh slastatus.sh
          name: "Armorcode Validate"
version: 2.1
workflows: 
  armorcode-validation-workflow: 
    jobs: 
      - armorcode-validate
