version: 2.1
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      product: test-o
      subProduct: test-sub-1
      environment: Staging
      token: fb5b3e66-ee6d-4af1-b70c-8a3236ad51cf
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
    steps:
      - run:
          name: "Armorcode Validate"
          command: |
              wget https://dev.armorcode.ai/static/scripts/slastatus.sh
              sh slastatus.sh
workflows:
  armorcode-validation-workflow:
    jobs:
      - armorcode-validate

